import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../styles/theme";
import Footer from "../Components/Footer";
import styles from "../styles/Home.module.css";

const Layout = ({ route, children, title }) => {
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="initial-scale=1, width=device-width" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ThemeProvider theme={theme}>
				<main className={styles.main}>
					<div styles={{ position: "relative", overflow: "hidden" }}>
						<video
							style={{
								objectFit: "cover",
								width: "100vw",
								height: "100vh",
								top: 0,
								left: 0,
								overflowY: "hidden",
							}}
							playsInline
							muted
							autoPlay
							loop
						>
							<source src="/waterdance.mp4" type="video/mp4" />
						</video>
						<div style={{ position: "absolute", top: 0, left: 0 }}>
							{children}
						</div>
						<div
							style={{
								position: "absolute",
								bottom: 0,
								left: 0,
								backgroundColor: "rgba(0,0,0,0)",
							}}
						>
							<Footer />
						</div>
					</div>
				</main>
			</ThemeProvider>
		</>
	);
};

export default Layout;
